"""empty message

Revision ID: 0514a719f6c3
Revises: bca5ce951da1
Create Date: 2024-03-08 12:10:47.449892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0514a719f6c3'
down_revision = 'bca5ce951da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('poster_url')

    # ### end Alembic commands ###
