"""Added new fields to Film model

Revision ID: bca5ce951da1
Revises: db003b639d6c
Create Date: 2024-03-07 14:04:13.606540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca5ce951da1'
down_revision = 'db003b639d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trailer_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bezoekers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('omzet', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('overzicht', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('overzicht')
        batch_op.drop_column('omzet')
        batch_op.drop_column('bezoekers')
        batch_op.drop_column('trailer_url')

    # ### end Alembic commands ###
