"""empty message

Revision ID: d07611747478
Revises: 
Create Date: 2024-03-08 13:53:03.265269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07611747478'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acteur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voornaam', sa.String(length=50), nullable=False),
    sa.Column('achternaam', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gebruiker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('wachtwoord_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('gebruiker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gebruiker_username'), ['username'], unique=True)

    op.create_table('regisseur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voornaam', sa.String(length=50), nullable=False),
    sa.Column('achternaam', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=100), nullable=False),
    sa.Column('regisseur_id', sa.Integer(), nullable=False),
    sa.Column('jaar', sa.Integer(), nullable=False),
    sa.Column('trailer_url', sa.String(length=255), nullable=True),
    sa.Column('poster_url', sa.String(length=255), nullable=True),
    sa.Column('bezoekers', sa.Integer(), nullable=True),
    sa.Column('omzet', sa.BigInteger(), nullable=True),
    sa.Column('overzicht', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['regisseur_id'], ['regisseur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citaat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inhoud', sa.Text(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['gebruiker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acteur_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('personage', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['acteur_id'], ['acteur.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rol')
    op.drop_table('citaat')
    op.drop_table('film')
    op.drop_table('regisseur')
    with op.batch_alter_table('gebruiker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gebruiker_username'))

    op.drop_table('gebruiker')
    op.drop_table('acteur')
    # ### end Alembic commands ###
